### PR TITLE
Major doc refactor

### PR DESCRIPTION
**Pull request by flanakin**
## 🛠️ Description
- Move FinOps documentation from MS Learn into the toolkit.
- Group related docs together.
- Add an upgrade guide for FinOps hubs.
- Add a data ingestion report.

See the sample site @ https://flanakin.github.io/finops-toolkit

### 🔬 How did you test this change?

> - [ ] 🤏 Lint tests
> - [ ] 🤞 PS -WhatIf / az validate
> - [x] 👍 Manually deployed + verified
> - [ ] 💪 Unit tests
> - [ ] 🙌 Integration tests

### 🙋‍♀️ Do any of the following that apply?

> - [ ] 🚨 This is a breaking change.
> - [ ] 🤏 The change is less than 20 lines of code.

### 📑 Did you update `docs/changelog.md`?

> - [ ] ✅ Yes (required for `dev` PRs)
> - [ ] ➡️ Will cover in a future PR (feature branch PRs only)
> - [x] ❎ Not needed (small/internal change)

### 📖 Did you update documentation?

> - [x] ✅ Public docs in `docs` (required for `dev`)
> - [ ] ✅ Internal dev docs in `src` (required for `dev`)
> - [ ] ➡️ Will cover in a future PR (feature branch PRs only)
> - [ ] ❎ Not needed (small/internal change)

### CODE REVIEW

**Comment by arthurclares** [comment]
https://flanakin.github.io/finops-toolkit/data#%EF%B8%8F-services Shouldn't this table include the ServiceModel(IaaS,PaaS,SaaS)?

**Comment by arthurclares** [comment]
Should we move the submenu "Implementing FinOps" to be the first one in the page? Thinking about this being the main FinOps page, we should first teach them what FinOps is before talking about tools.
Also, consider creating an explicit page for Learning Resources and Interactive guides under Implementing FinOps
image

**Comment by arthurclares** [comment]
A couple of "Deploy to Azure" buttons are broken in the Workbook "Customize" page. We can fix that after the migration, as I will need to update the screenshots to show some of the more interesting pages. I'm just adding this here to keep it in our radar.
https://flanakin.github.io/finops-toolkit/optimization-workbook/customize

**Review by arthurclares — CHANGES_REQUESTED** [review]
I have validate that all links are working, with the exception of a few Deploy to Azure buttons.  Apart from that, I ahve made a few suggestions to change some of the menu items.

**Comment by flanakin** [comment]
> https://flanakin.github.io/finops-toolkit/data#%EF%B8%8F-services Shouldn't this table include the ServiceModel(IaaS,PaaS,SaaS)?

Good catch. This was missed in the ServiceModel PR. @ymehdimsft can you submit a PR for this?

**Comment by flanakin** [comment]
> Should we move the submenu "Implementing FinOps" to be the first one in the page? Thinking about this being the main FinOps page, we should first teach them what FinOps is before talking about tools. 

Good call! I'll make that change.

> Also, consider creating an explicit page for Learning Resources and Interactive guides under Implementing FinOps

Yeah, I was thinking the same thing. I just didn't want to drag the release out longer. Let's do that in a separate PR.

**Comment by flanakin** [comment]
> Should we move the Deployment Options to the Reporting+Analytics section? This page has a lot of good information and I think it's kind of hidden inside of the "Resources" section now.

It applies to all templates and is already linked to from each of the template pages. Let's talk about it and come up with a plan in a separate PR.

**Comment by flanakin** [comment]
> A couple of "Deploy to Azure" buttons are broken in the Workbook "Customize" page. We can fix that after the migration, as I will need to update the screenshots to show some of the more interesting pages. I'm just adding this here to keep it in our radar. https://flanakin.github.io/finops-toolkit/optimization-workbook/customize

Another great catch! Updated!

**Comment by flanakin** [comment]
> Lastly, should 'FOCUS' have its dedicated section, or is it more fitting to be included as part of the 'Implementing FinOps' section? I feel like there is a ton of useful information there as well, so might help if we have a dedicated section instead.

Hmm... 🤔 Maybe... I was a bit torn. I wouldn't want a single page to have its own section. And too many sections with only a few items probably isn't great. Let's think about this and split it out in a separate PR if we think there's a better organization. I'm all for breaking things out.

**Comment by arthurclares** [comment]
As you are doing this major review, can you also update this section and include this link to help customers adding historical data?
image
 https://learn.microsoft.com/en-us/azure/cost-management-billing/automate/tutorial-seed-historical-cost-dataset-exports-api

**Pull request merged**
