### PR TITLE
Add region mapping file

### PR DESCRIPTION
**Pull request by flanakin**
## 🛠️ Description
Add a region mapping file to help people map inconsistent resource location values to standard Azure region IDs and names.

## 📷 Screenshots
Screenshot of the mapping file showing the type, value, ID, and name columns

### 📑 Did you update `docs/changelog.md`?

- [x] ✅ Yes (required for `dev` PRs)
- [ ] ➡️ Will cover in a future PR (feature branch PRs only)
- [ ] ❎ Not needed (small/internal change)

### 📖 Did you update documentation?

- [x] ✅ Public docs in `docs` (required for `dev`)
- [ ] ✅ Internal dev docs in `src` (required for `dev`)
- [ ] ➡️ Will cover in a future PR (feature branch PRs only)
- [ ] ❎ Not needed (small/internal change)

### CODE REVIEW

**Comment by flanakin** [comment]
@all-contributors please add soumyananda for review

**Comment by flanakin** [comment]
https://github.com/all-contributors please add soumyananda for review

**Comment by flanakin** [comment]
@all-contributors please add soumyananda for review

**Comment by soumyananda** [comment]
The region name mapping looks good and complete!

**Comment by chandra-cloudtrakr** [comment]
@flanakin  Here is my feedback for RegionId. In general, ID refers to a unique identifier which is not easily (human) readable. Using "code" for id would be a better option such as RegionCode, which the value is human readable. Code is not unique but referred uniquely. But if ID is used consistently for other columns, then RegionId is suitable.

**Pull request merged**
