### PR TITLE
Hubs ADX ingestion out of memory fix

### LINKED ISSUE #1188: Cost_Final table update policy fails with out of memory exception.
## 🐛 Issue  
During data ingestion, the `Cost_Final_V1_0` update policy (function `Costs_transform_v1_0`) fails due to an "out of memory" exception.

## 👣 Steps to Reproduce  

1. **Setup**  
   - Configure the FinOps Toolkit with the default settings, using the smallest ADX SKU.  

2. **Prepare Data**  
   - Ensure price data has already been ingested.  

3. **Trigger Issue**  
   - Ingest 50 MB of cost data in Snappy-compressed Parquet format.  

4. **Verify Ingestion Failure**  
   - Run the command `.show ingestion failures` in the ingestion database.  
   - Confirm the presence of an "out of memory" exception.  

5. **Verify Operation Failure**  
   - Run the command `.show operations` in the ingestion database.  
   - Confirm that the `Costs_transform_v1_0` update policy has failed.  

## 🤔 Expected Outcome  
The ingestion process should successfully complete without any errors.  
- No "out of memory" exceptions should occur during the operation.  
- The `Costs_transform_v1_0` update policy should execute without failures, ensuring proper data transformation and ingestion.

## ℹ️ Additional context
I suspect that the join in the Costs_transform_v1_0 function might be part of the problem. It could potentially be replaced with a lookup. Maybe other KQL optimizations apply such as materializing the price lookup before joining.

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

### PR DESCRIPTION
**Pull request by flanakin**
## 🛠️ Description
Improve performance and memory consumption of the Costs_transform_v1_0() KQL function

Fixes #1188

### 🔬 How did you test this change?

> - [ ] 🤏 Lint tests
> - [ ] 🤞 PS -WhatIf / az validate
> - [x] 👍 Manually deployed + verified
> - [ ] 💪 Unit tests
> - [ ] 🙌 Integration tests

### 🙋‍♀️ Do any of the following that apply?

> - [ ] 🚨 This is a breaking change.
> - [x] 🤏 The change is less than 20 lines of code.

### 📑 Did you update `docs/changelog.md`?

> - [x] ✅ Updated changelog (required for `dev` PRs)
> - [ ] ➡️ Will add log in a future PR (feature branch PRs only)
> - [ ] ❎ Log not needed (small/internal change)

### 📖 Did you update documentation?

> - [ ] ✅ Public docs in `docs` (required for `dev`)
> - [ ] ✅ Internal dev docs in `src` (required for `dev`)
> - [ ] ➡️ Will add docs in a future PR (feature branch PRs only)
> - [x] ❎ Docs not needed (small/internal change)

### CODE REVIEW

**Comment by RolandKrummenacher** [comment]
I was able to reproduce the out of memory exception in my test environment:

image

I've tried to ingest a single snappy.parquet file:

image

image

Cluster size is Dev(No SLA)_Standard_D11_v2

**Comment by RolandKrummenacher** [comment]
By applying the fix in this PR, I was able to ingest the file successfully:

image

**Review by RolandKrummenacher — APPROVED** [review]
See comments

**Comment by flanakin** [comment]
@allcontributors please add RolandKrummenacher for review

**Pull request merged**
