### PR TITLE
Add main.bicep file for waste reduction logic app

### PR DESCRIPTION
**Pull request by ro100e**
## 🛠️ Description
Converted logic app to bicep to create main.bicep file following guidelines
 Created blank .json and .md files that follow QuickStart guidelines

### 🔬 How did you test this change?

> - [ ] 🤏 Lint tests
> - [ ] 🤞 PS -WhatIf / az validate
> - [x] 👍 Manually deployed + verified
> - [ ] 💪 Unit tests
> - [ ] 🙌 Integration tests

### 🙋‍♀️ Do any of the following that apply?

> - [x] 🚨 This is a breaking change.
> - [ ] 🤏 The change is less than 20 lines of code.

### 📑 Did you update `docs/changelog.md`?

> - [ ] ✅ Yes (required for `dev` PRs)
> - [x] ➡️ Will cover in a future PR (feature branch PRs only)
> - [ ] ❎ Not needed (small/internal change)

### 📖 Did you update documentation?

> - [ ] ✅ Public docs in `docs` (required for `dev`)
> - [ ] ✅ Internal dev docs in `src` (required for `dev`)
> - [x] ➡️ Will cover in a future PR (feature branch PRs only)
> - [ ] ❎ Not needed (small/internal change)

### CODE REVIEW

**Comment by flanakin** [comment]
Should this go to the `features/alerts` branch?

FYI - You can edit the PR to switch branches, in case you didn't know already.

**Comment by ro100e** [comment]
> Should this go to the `features/alerts` branch?
> 
> FYI - You can edit the PR to switch branches, in case you didn't know already.

Yes! missed this thanks for catching that

**Review by arthurclares — APPROVED** [review]
I made a few updates to the bicep file: Add a few parameters, variables and outputs.

**Comment by ro100e** [comment]
> @ro100e Before we merge this, can you test it one more time now that I added the parameters.

Tested, works, thanks for fixed the warning about hardcoded uri's

**Pull request merged**
